name: Linting

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  phpcs:
    name: phpcs
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: composer install
      run: composer install
    - name: PHPCS check
      uses: chekalsky/phpcs-action@v1
      with:
        phpcs_bin_path: './vendor/bin/phpcs'
